-- Script to create negocio_db and required tables
DROP DATABASE IF EXISTS negocio_db;
CREATE DATABASE negocio_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE negocio_db;

-- Tabla de usuarios
CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  usuario VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  rol ENUM('admin','vendedor','cajero') DEFAULT 'vendedor'
);

-- Tabla de productos
CREATE TABLE productos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion TEXT,
  precio DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de ventas
CREATE TABLE ventas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  total DECIMAL(10,2) NOT NULL,
  usuario_id INT,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- Detalle de cada venta
CREATE TABLE detalle_venta (
  id INT AUTO_INCREMENT PRIMARY KEY,
  venta_id INT,
  producto_id INT,
  cantidad INT NOT NULL,
  precio_unitario DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (venta_id) REFERENCES ventas(id) ON DELETE CASCADE,
  FOREIGN KEY (producto_id) REFERENCES productos(id) ON DELETE SET NULL
);

-- Tabla de caja
CREATE TABLE caja (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fecha DATE NOT NULL,
  apertura DECIMAL(10,2) NOT NULL,
  cierre DECIMAL(10,2),
  usuario_id INT,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- Movimientos de caja
CREATE TABLE movimientos_caja (
  id INT AUTO_INCREMENT PRIMARY KEY,
  caja_id INT,
  descripcion VARCHAR(255),
  monto DECIMAL(10,2) NOT NULL,
  tipo ENUM('entrada','salida') NOT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (caja_id) REFERENCES caja(id) ON DELETE CASCADE
);

-- Insert sample admin user (password: admin123) - hashed value placeholder
-- You should replace this hash with one generated by bcrypt if desired.
INSERT INTO usuarios (nombre, usuario, password, rol) VALUES ('Admin','admin','$2b$10$KIXQm2y1G0y1jQ/8Zs9sZOlcJc7rYQxq0xQeG1YH6m0Yc6G5e1u6e','admin');

-- Insert some sample products
INSERT INTO productos (nombre, descripcion, precio, stock) VALUES
('Producto A', 'Descripcion A', 100.00, 10),
('Producto B', 'Descripcion B', 50.00, 20),
('Producto C', 'Descripcion C', 10.00, 100);
