-- Script to create negocio_db and required tables
DROP DATABASE IF EXISTS negocio_db;
CREATE DATABASE negocio_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE negocio_db;

-- Tabla de usuarios
-- Añadimos los estados 'pendiente' y 'moderador'. El valor por defecto al registrarse será 'pendiente'.
CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  usuario VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  rol ENUM('admin','moderador','vendedor','cajero','pendiente') DEFAULT 'pendiente'
);

CREATE TABLE productos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion TEXT,
  precio DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  proveedor_id INT NULL,
  categoria VARCHAR(100) NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (proveedor_id) REFERENCES proveedores(id) ON DELETE SET NULL
);
-- Nueva columna: categoria y proveedor ya incluidas en la tabla

-- Tabla proveedores
CREATE TABLE IF NOT EXISTS proveedores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  contacto VARCHAR(255),
  telefono VARCHAR(64),
  email VARCHAR(255),
  direccion TEXT,
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Pedidos a proveedores (cabecera)
CREATE TABLE IF NOT EXISTS pedidos_proveedor (
  id INT AUTO_INCREMENT PRIMARY KEY,
  proveedor_id INT NOT NULL,
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(50) DEFAULT 'pendiente',
  notas TEXT,
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (proveedor_id) REFERENCES proveedores(id)
);

-- Items de cada pedido a proveedor
CREATE TABLE IF NOT EXISTS pedido_proveedor_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pedido_id INT NOT NULL,
  producto_id INT NOT NULL,
  cantidad INT NOT NULL,
  precio_unitario DECIMAL(10,2) DEFAULT 0,
  FOREIGN KEY (pedido_id) REFERENCES pedidos_proveedor(id),
  FOREIGN KEY (producto_id) REFERENCES productos(id)
);

-- Tabla de ventas
CREATE TABLE ventas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  total DECIMAL(10,2) NOT NULL,
  tipo_factura VARCHAR(50) DEFAULT NULL,
  usuario_id INT,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- Tabla de clientes (para envíos)
CREATE TABLE clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  telefono VARCHAR(50),
  email VARCHAR(100),
  direccion TEXT,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de pedidos: registra envíos asociados a una venta y un cliente
CREATE TABLE pedidos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  venta_id INT NOT NULL,
  cliente_id INT NOT NULL,
  direccion TEXT NOT NULL,
  fecha_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  estado ENUM('pendiente','enviado','entregado') DEFAULT 'pendiente',
  notas TEXT,
  FOREIGN KEY (venta_id) REFERENCES ventas(id) ON DELETE CASCADE,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);

-- Detalle de cada venta
CREATE TABLE detalle_venta (
  id INT AUTO_INCREMENT PRIMARY KEY,
  venta_id INT,
  producto_id INT,
  cantidad INT NOT NULL,
  precio_unitario DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (venta_id) REFERENCES ventas(id) ON DELETE CASCADE,
  FOREIGN KEY (producto_id) REFERENCES productos(id) ON DELETE SET NULL
);

-- Tabla de caja
CREATE TABLE caja (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fecha DATE NOT NULL,
  apertura DECIMAL(10,2) NOT NULL,
  cierre DECIMAL(10,2),
  usuario_id INT,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- Movimientos de caja
CREATE TABLE movimientos_caja (
  id INT AUTO_INCREMENT PRIMARY KEY,
  caja_id INT,
  pago_id INT NULL,
  descripcion VARCHAR(255),
  monto DECIMAL(10,2) NOT NULL,
  tipo ENUM('entrada','salida') NOT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (caja_id) REFERENCES caja(id) ON DELETE CASCADE,
  FOREIGN KEY (pago_id) REFERENCES pagos(id) ON DELETE SET NULL
);

-- Tabla de pagos (vinculada a ventas)
CREATE TABLE pagos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  venta_id INT NOT NULL,
  tipo_pago ENUM('efectivo', 'tarjeta', 'qr', 'transferencia') NOT NULL,
  monto DECIMAL(10,2) NOT NULL,
  estado ENUM('pendiente','procesado','cancelado','anulado') DEFAULT 'procesado',
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  notas TEXT,
  FOREIGN KEY (venta_id) REFERENCES ventas(id) ON DELETE CASCADE
);

-- Insert sample admin user (password: admin123) - hashed value placeholder
-- You should replace this hash with one generated by bcrypt if desired.
INSERT INTO usuarios (nombre, usuario, password, rol) VALUES ('Admin','admin','$2b$10$KIXQm2y1G0y1jQ/8Zs9sZOlcJc7rYQxq0xQeG1YH6m0Yc6G5e1u6e','admin');

-- Insert some sample products
INSERT INTO productos (nombre, descripcion, precio, stock) VALUES
('Producto A', 'Descripcion A', 100.00, 10),
('Producto B', 'Descripcion B', 50.00, 20),
('Producto C', 'Descripcion C', 10.00, 100);
